### ISSUE TITLE
Adding collision to rendinst

### ISSUE THREAD

**Issue by VeresBalazsLaszlo** [GaijinEntertainment/DagorEngine#100]
I have exported a rendinst using 3ds max, and later assetviewer, but i can't figure out how to add collision to said rendinst.
I have searched the documentation, but in vain.

Do .DAG files need to contain collision data before exporting? If so, how is it added to the model?

**Comment by NicSavichev** [comment]
I think documentation still misses this. For each rendInst loaded (name it XXX) engine tries to load collision resource with name XXX_collision. Asset type is collision, see file `X:\DagorEngine.git\outerSpace\develop\assets\gaija_planet\terrain\entities\vegetation\.folder.blk` for example how both collision and rendInst assets are created for the same DAG file.
To be collidable nodes in DAG should contain `Collidable` flag, e.g.
node{
  Renderable:b=yes
  Castshadow:b=yes
  Collidable:b=yes

**Comment by VeresBalazsLaszlo** [comment]
Thank you, i have managed to load the collisions.
