### ISSUE TITLE
200 GB of HDD/SSD?

### ISSUE THREAD

**Issue by uteal** [GaijinEntertainment/DagorEngine#101]
Is this a typo? Or does the engine come with a comprehensive library of graphics assets?

**Comment by Subhanshu-2411** [comment]
Unreal Engine and Unity are also Memory & RAM heavy, This might not be the actual requirement but the projects made and deployed also takes up a lot of space

**Comment by NicSavichev** [comment]
Full size of DagorEngine folder (with unpacked source binary data and with built binary data)  is 60Gb for Windows, where `_output` folder takes 38Gb.
Also `devtools` folder required to build engine/tools from sources is 21Gb.
So I think 80Gb is minimum required space to install and rebuild everything from scratch.
If you build only daNetGame-based project (and use other tools as prebuilt) you will need only 4Gb in `_output`.
But if you start real project better prepare for hundreds of Gb for `develop` and for 2-10Gb for final deployable `game`.
