### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Jojoman632** [GaijinEntertainment/DagorEngine#105]
My Current Hardware is amd 5800h and rtx3060. Any Kind of help would be greatly appreciated. Thanks

--- Running: build_dagor_cdk_mini.cmd  in  prog/tools

----------------------------------------------------------------------

...failed lib_target ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/3rdPartyLibs/breakpad~zng.lib ...
FAILED to build windows.lib [Error #-1] [windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex]

...failed lib_target ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/3rdPartyLibs/minhook.lib .
----------------------------------------------------------------------
FAILED to build mimalloc.lib [Error #-1] [windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex]
.
...
----------------------------------------------------------------------

...failed lib_target ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/3rdPartyLibs/mimalloc.lib ...
FAILED to build sha.lib [Error #-1] [windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex]
.

...failed lib_target ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/3rdPartyLibs/breakpad/common/windows.lib ...
FAILED to build rtlOverride.lib [Error #-1] [windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex]
.

...failed lib_target ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/3rdPartyLibs/openssl-3.x/crypto/sha.lib ...

...failed lib_target ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/engine/memory/rtlOverride.lib ...
D:\DagorEngine\prog\engine\osApiWrappers\cpuFeatures.cpp(18,10): fatal error: 'cpuid.h' file not found
#include <cpuid.h>
         ^~~~~~~~~
1 error generated.
In file included from ..\..\prog\3rdPartyLibs\hash\xxhash.c:43:
D:\DagorEngine\prog\3rdPartyLibs\hash\xxhash.h(1165,12): fatal error: 'stdalign.h' file not found
#  include <stdalign.h>
           ^~~~~~~~~~~~
D:\DagorEngine\prog\engine\kernel\perfTimer.cpp(155,10): fatal error: 'cpuid.h' file not found
#include <cpuid.h>
         ^~~~~~~~~
1 error generated.
D:\DagorEngine\prog\3rdPartyLibs\hash\sha1.cpp(13,3): error: static assertion expression is not an integral constant expression
  G_STATIC_ASSERT(offsetof(sha1_context, total) >= sizeof(SHA_CTX));
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\DagorEngine\prog\dagorInclude\debug\dag_assert.h(185,42): note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(x) static_assert((x), "assertion failed: " #x)
                                         ^~~
D:\DagorEngine\prog\3rdPartyLibs\hash\sha1.cpp(13,19): note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
  G_STATIC_ASSERT(offsetof(sha1_context, total) >= sizeof(SHA_CTX));
                  ^
D:\DagorEngine\devtools\win.sdk.100\include\10.0.19041.0\ucrt\stddef.h(47,32): note: expanded from macro 'offsetof'
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
                               ^
1 error generated.
In file included from ..\..\prog\3rdPartyLibs\arc\zstd-1.4.5\decompress\zstd_decompress.c:59:
D:\DagorEngine\prog\3rdPartyLibs\arc\zstd-1.4.5\common\cpu.h(27,10): fatal error: 'cpuid.h' file not found
#include <cpuid.h>
         ^~~~~~~~~
In file included from ..\..\prog\3rdPartyLibs\arc\zstd-1.4.5\decompress\zstd_decompress_block.c:19:
D:\DagorEngine\prog\3rdPartyLibs\arc\zstd-1.4.5\common\cpu.h(27,10): fatal error: 'cpuid.h' file not found
#include <cpuid.h>
         ^~~~~~~~~
In file included from ..\..\prog\3rdPartyLibs\arc\zstd-1.4.5\decompress\zstd_ddict.c:18:
D:\DagorEngine\prog\3rdPartyLibs\arc\zstd-1.4.5\common\cpu.h(27,10): fatal error: 'cpuid.h' file not found
#include <cpuid.h>
         ^~~~~~~~~
In file included from ..\..\prog\3rdPartyLibs\arc\zstd-1.4.5\compress\zstd_compress.c:16:
D:\DagorEngine\prog\3rdPartyLibs\arc\zstd-1.4.5\common\cpu.h(27,10): fatal error: 'cpuid.h' file not found
#include <cpuid.h>
         ^~~~~~~~~
1 error generated.
1 error generated.
1 error generated.
1 error generated.

...failed compile_c ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_3rdPartyLibs/arc/zstd-1.4.5.lib/decompress/zstd_ddict.obj ...

...failed compile_c ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_3rdPartyLibs/arc/zstd-1.4.5.lib/decompress/zstd_decompress.obj ...

...failed compile_c ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_3rdPartyLibs/arc/zstd-1.4.5.lib/decompress/zstd_decompress_block.obj ...
1 error generated.

...failed compile_cpp ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_3rdPartyLibs/hash.lib/sha1.obj ...

...failed compile_c ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_3rdPartyLibs/hash.lib/xxhash.obj ...
...skipped ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/3rdPartyLibs/hash.lib for lack of ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_3rdPartyLibs/hash.lib/sha1.obj...

...failed compile_c ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_3rdPartyLibs/arc/zstd-1.4.5.lib/compress/zstd_compress.obj ...
...skipped ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/3rdPartyLibs/arc/zstd-1.4.5.lib for lack of ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_3rdPartyLibs/arc/zstd-1.4.5.lib/compress/zstd_compress.obj...
D:\DagorEngine\prog\engine\startup\checkCpuid.cpp(14,10): fatal error: 'cpuid.h' file not found
#include <cpuid.h>
         ^~~~~~~~~
1 error generated.
D:\DagorEngine\prog\engine\math\wooray2d.cpp(13,3): error: static assertion expression is not an integral constant expression
  G_STATIC_ASSERT(offsetof(WooRay2d, endCell) == offsetof(WooRay2d, pt) + 8);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:\DagorEngine\prog\dagorInclude\debug\dag_assert.h(185,42): note: expanded from macro 'G_STATIC_ASSERT'
#define G_STATIC_ASSERT(x) static_assert((x), "assertion failed: " #x)
                                         ^~~
D:\DagorEngine\prog\engine\math\wooray2d.cpp(13,19): note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
  G_STATIC_ASSERT(offsetof(WooRay2d, endCell) == offsetof(WooRay2d, pt) + 8);
                  ^
D:\DagorEngine\devtools\win.sdk.100\include\10.0.19041.0\ucrt\stddef.h(47,32): note: expanded from macro 'offsetof'
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
                               ^
1 error generated.

...failed compile_cpp ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_engine/osApiWrappers.lib/cpuFeatures.obj ...
...skipped ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/engine/osApiWrappers.lib for lack of ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_engine/osApiWrappers.lib/cpuFeatures.obj...

...failed compile_cpp ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_engine/kernel.lib/perfTimer.obj ...
...skipped ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/engine/kernel.lib for lack of ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_engine/kernel.lib/perfTimer.obj...

...failed compile_cpp ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_engine/startup.lib/checkCpuid.obj ...
...skipped ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/engine/startup.lib for lack of ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_engine/startup.lib/checkCpuid.obj...

...failed compile_cpp ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_engine/math.lib/wooray2d.obj ...
...skipped ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/engine/math.lib for lack of ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/_engine/math.lib/wooray2d.obj...
...skipped ../../tools/dagor_cdk/windows-x86_64/dsc2-hlsl11-dev.exe for lack of ../../_output/windows-100~x86_64~dev~clang-15.0.7~cpp20~s2~fp~ex/3rdPartyLibs/eastl.lib...
...skipped ../../tools/dagor_cdk/windows-x86_64/dsc2-hlsl11-dev-STAMP for lack of ../../tools/dagor_cdk/windows-x86_64/dsc2-hlsl11-dev.exe...
generated LICENSE-dsc2-hlsl11-dev
...failed updating 33 target(s)...
...skipped 8 target(s)...
...updated 3 target(s)...

build time: 0.1 sec (graph), 1.8 sec (actions), using 17 job(s)

An error occured
subprocess.run failed with a non-zero exit code. Error: Command 'build_dagor_cdk_mini.cmd' returned non-zero exit status 1.
echo failed to build CDK, stop!

**Comment by NicSavichev** [comment]
what clang version do you use to compile? `make_devtools.py` is expected to install 15.0.7 and it is tested to compile code successfully.

**Comment by Jojoman632** [comment]
Hi thanks for the response. I was able to get over this error by downloading and installing the llvm-15.0.7 for myself, The script version does not work for me atm. i am getting another error and cmd freezes up on me with this and opens __build_pack.py located in prog/tools/dag4blend.


build time: 1.5 sec (graph), 0.0 sec (actions), using 17 job(s)

[main 2024-12-20T00:23:37.091Z] update#setState idle
(node:20604) [DEP0168] DeprecationWarning: Uncaught N-API callback exception detected, please run node with option --force-node-api-uncaught-exceptions-policy=true to handle those exceptions properly.
(Use `Code --trace-deprecation ...` to show where the warning was created)
[main 2024-12-20T00:24:07.102Z] update#setState checking for updates
[main 2024-12-20T00:24:07.191Z] update#setState idle

**Comment by Jojoman632** [comment]
Hi i solved the above issue as well. thanks
