### ISSUE TITLE
Questions about engine development

### ISSUE THREAD

**Issue by RuanLucasGD** [GaijinEntertainment/DagorEngine#11]
Hello, i'm glad to see the War Thunder engine XD, it's my favorite game, but i have some doubts about the development of this engine.

1. There is a roadmap for next features/fixes?
2. There is a documentation/manual/guide (instead samples) ?
3. Any community ?
4. This engine is open to new contribuitors ?
5. Can i use Dagor for my games?

**Comment by AntMaster7** [comment]
@RuanLucasGD You can use Dagor for your own games. See the LICENSE file which states that the source code is released under the BSD 3-Clause license.

**Comment by Mrkol** [comment]
1. There is one, but it's not public yet.
2. No guides/manuals yet, sorry. Documentation is WIP.
3. Hopefully in the future?
4. Idk, in theory, yes, but in practice we don't have a contributors agreement yet.
5. Yes, see the license
