### ISSUE TITLE
Failed to load some file...

### ISSUE THREAD

**Issue by Geskawary234** [GaijinEntertainment/DagorEngine#15]
![изображение](https://github.com/GaijinEntertainment/DagorEngine/assets/113011647/a809875b-df56-4695-9031-e1d9c77a224e)
I downloaded prebuilt

**Comment by JustMinna** [comment]
Getting issues from prebuilt too
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/148638276/ae760caa-81ce-4f89-a4f6-e34deb6b4a77)

**Comment by LakoMoor** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/44299427/54add24c-1096-48de-8ae1-e5e6afca81df)
Same...

**Comment by LakoMoor** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/44299427/e59f285d-82a7-44bf-8560-ed9b587e59ac)
I try download old release [tools-prebuilt.7z](https://github.com/GaijinEntertainment/DagorEngine/releases/download/dagor_2023_09_15/tools-prebuilt.7z). It has an APK file for android. It managed to be launched

**Comment by LakoMoor** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/44299427/f9643f49-e37d-44a0-bc8d-9628aa28912c)
benchmark

**Comment by NicSavichev** [comment]
prebuilt binaries are supposed to be placed INSIDE git repo (so it can find used files in sources).
if you use binaries apart from git repo then
```
debug {
  useVromSrc:b=no
```
must be specified in tools\dargBox\settings.blk to read data from vromfs (instead of reading source scripts form repo)

**Comment by LakoMoor** [comment]
> prebuilt binaries are supposed to be placed INSIDE git repo (so it can find used files in sources). if you use binaries apart from git repo then
> 
> ```
> debug {
>   useVromSrc:b=no
> ```
> 
> must be specified in tools\dargBox\settings.blk to read data from vromfs (instead of reading source scripts form repo)

Yep. This working!))
