### ISSUE TITLE
[Question]  About the Blender extension..

### ISSUE THREAD

**Issue by Roskavaki** [GaijinEntertainment/DagorEngine#16]
I have some questions about using Blender to create models for DagorEngine.

I'm interested in using the Blender extension to make models for WarThunder.  The Blender extension included in the WarThunder CDK only works with older versions of Blender, and doesn't keep objects separate (all meshes are combined into 1, so it is not useful for creating aircraft).   Therefore I thought I would try dag4blend in this project.

**1)  What version of Blender should I use?**
I've tried zipping the contents of dag4blend into a file called bl_dag_exporter.zip and then in Blender, preferences->addons->install    But I don't see the addon added to the list of installed add-ons.  I have tried in Blender 2.49b,  2.71, 3.3.0

**2) Do I need to build blk2dag to export from Blender to Dagor?**   The extension in the Thunder CDK depended upon blk2dag.exe so I am wondering if this is still a requirement.

3) If the answer to 2 is yes, then **do I need to build the whole DagorEngine, or can blk2dag be built by itself?**

**Comment by seanballais** [comment]
Seems like the plugin is designed for Blender 3.1.2. Maybe try that and see what happens?

**Comment by NicSavichev** [comment]
> 3. If the answer to 2 is yes, then **do I need to build the whole DagorEngine, or can blk2dag be built by itself?**

Please wait couple of days, we will update Blender plugin to actual working version shortly

**Comment by NicSavichev** [comment]
updated Blender plugin script [change here](https://github.com/GaijinEntertainment/DagorEngine/commit/0427e7f4229c5cae08f88693da6fff57c55b7aea)
updated repo and build with `pack.bat` in `DagorEngine.git/prog/tools/dag4blend`
then install resulting `dag4blend.zip` to Blender

**Comment by Roskavaki** [comment]
Thankyou very much!


I'm not able to see the cube.dag I created in the warthunder AssetViewer, but it's probably something I am doing wrong.

If anyone else comes to this thread using Windows, you may need to install 7zip, add 7zip to your path, then edit pack.bat and replace 
`zip dag4blend\dag4blend.zip`
with
`7z.exe a -tzip dag4blend\dag4blend.zip`

**Comment by Roskavaki** [comment]
Ok, I was using a blender version that was <3.5 now I can see objects in assetviewer.
