### ISSUE TITLE
[Question] How to build lighting?

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#17]
It seems the lighting plugin is not included currently.

**Comment by NicSavichev** [comment]
> It seems the lighting plugin is not included currently.

prebuilt lighting (lightmaps and vertex-lightmaps) was dropped in DagorEngine several years ago, plugin Light is not used anymore. Dynamic lighng (defered shading with gbuffer) is used

**Comment by CodeLikeCXK** [comment]
> > It seems the lighting plugin is not included currently.
> 
> prebuilt lighting (lightmaps and vertex-lightmaps) was dropped in DagorEngine several years ago, plugin Light is not used anymore. Dynamic lighng (defered shading with gbuffer) is used

I see. So why in editor. the dark part of sponza scene is too dark unlike the prebuilt game sample?How to solve that?
Also in editor, the plugin Light is turned on in environment setting and can't switch to direct lighting.

**Comment by NicSavichev** [comment]
> > > It seems the lighting plugin is not included currently.
> > 
> > 
> > prebuilt lighting (lightmaps and vertex-lightmaps) was dropped in DagorEngine several years ago, plugin Light is not used anymore. Dynamic lighng (defered shading with gbuffer) is used
> 
> I see. So why in editor. the dark part of sponza scene is too dark unlike the prebuilt game sample?How to solve that? Also in editor, the plugin Light is turned on in project setting and can't switch to direct lighting. Even after switching to direct light and apply and press OK, the preview shows no difference. ![image](https://user-images.githubusercontent.com/44729188/285154016-f3d15bdd-4f8c-4f78-9265-85a038816cd3.png)

This is due to editor doesn't use Global Illumination and ambient is not set at all/ This scene is not very good to look in the editor

**Comment by CodeLikeCXK** [comment]
> > > > It seems the lighting plugin is not included currently.
> > > 
> > > 
> > > prebuilt lighting (lightmaps and vertex-lightmaps) was dropped in DagorEngine several years ago, plugin Light is not used anymore. Dynamic lighng (defered shading with gbuffer) is used
> > 
> > 
> > I see. So why in editor. the dark part of sponza scene is too dark unlike the prebuilt game sample?How to solve that? Also in editor, the plugin Light is turned on in project setting and can't switch to direct lighting. Even after switching to direct light and apply and press OK, the preview shows no difference. ![image](https://user-images.githubusercontent.com/44729188/285154016-f3d15bdd-4f8c-4f78-9265-85a038816cd3.png)
> 
> This is due to editor doesn't use Global Illumination and ambient is not set at all/ This scene is not very good to look in the editor

I see...So why after I change light and export the level, the scene looks totally dark in game?
![editor](https://github.com/GaijinEntertainment/DagorEngine/assets/44729188/143fd00b-c462-4a5c-947d-ddcee4e38fb3)
![game](https://github.com/GaijinEntertainment/DagorEngine/assets/44729188/03d938de-3306-442f-a571-fafca0309224)

**Comment by CodeLikeCXK** [comment]
> > > > It seems the lighting plugin is not included currently.
> > > 
> > > 
> > > prebuilt lighting (lightmaps and vertex-lightmaps) was dropped in DagorEngine several years ago, plugin Light is not used anymore. Dynamic lighng (defered shading with gbuffer) is used
> > 
> > 
> > I see. So why in editor. the dark part of sponza scene is too dark unlike the prebuilt game sample?How to solve that? Also in editor, the plugin Light is turned on in project setting and can't switch to direct lighting. Even after switching to direct light and apply and press OK, the preview shows no difference. ![image](https://user-images.githubusercontent.com/44729188/285154016-f3d15bdd-4f8c-4f78-9265-85a038816cd3.png)
> 
> This is due to editor doesn't use Global Illumination and ambient is not set at all/ This scene is not very good to look in the editor

![image](https://github.com/GaijinEntertainment/DagorEngine/assets/44729188/1906f7c9-f3e9-4a17-a313-e93b7522b82b)
By the way. This is how the same map looks like in samples-prebuilt(I replace the map file with the one I output in editor), which means the error may come from the engine I built.
How could I find the problem?

**Comment by Capewearer** [comment]
@CodeLikeCXK if your TestGI sample lacks lighting bounces, press F2, you'll open ImGUI menu, so you can find option that enables light bouncing.
@NicSavichev is there still option to bake indirect lighting? You mentioned that lightmaps were cut, but do light probes still remain?
