### ISSUE TITLE
Built it myself (no prebuilt) , and these errors came up. (new to dagor pls help)

### ISSUE THREAD

**Issue by marcikaa78** [GaijinEntertainment/DagorEngine#18]
These errors were at TestGI ![Screenshot 2023-11-18 143004](https://github.com/GaijinEntertainment/DagorEngine/assets/132925550/1d2f45f5-a4c3-4958-bfac-eaf0e280c044)
![Screenshot 2023-11-18 143033](https://github.com/GaijinEntertainment/DagorEngine/assets/132925550/a45532f9-5c5c-421c-8b45-9b496f0f1ce8)

This error was at DaEditor ![Screenshot 2023-11-18 144145](https://github.com/GaijinEntertainment/DagorEngine/assets/132925550/60446f58-503f-4bf8-8d81-98828263fb07)

That was at DargBox ![Screenshot 2023-11-18 144911](https://github.com/GaijinEntertainment/DagorEngine/assets/132925550/d4e7482c-ad58-4210-bc57-786698c72477)

Please help me with this.

PS.: sorry if im annoying, I'm new :), and how to edit daEditor (and tools) like editing the splash screen editing the editor ui, and how to create a new project

**Comment by NicSavichev** [comment]
Did you unpack *-base.7z (tools and samples folders) prior to building? It seems not.
These archives contain binary data needed for tools and samples (binary data is not included to repo, it is to be downloaded from 'Releases' page)

**Comment by marcikaa78** [comment]
Thank you. And can you edit the daEditor code? If yes where do I find it?

**Comment by NicSavichev** [comment]
> Thank you. And can you edit the daEditor code? (Splash screen, dialogs, tools, etc..) If yes where do I find it?

daEditorX itself is here prog/tools/sceneTools/daEditorX
and base GUI libs are here: prog/tools/libTools/propPanel2 prog/tools/libTools/sepGui prog/tools/libTools/winGuiWrapper

**Comment by marcikaa78** [comment]
And what is DargBox? (sorry for many questions)

**Comment by NicSavichev** [comment]
> And what is DargBox? (sorry for many questions)

DargBox is tool to test GUI (daRg stays for dagor reactive gui)

**Comment by marcikaa78** [comment]
How to create a project and necessary .blk files?

**Comment by NicSavichev** [comment]
> How to create a project and necessary .blk files?

For now I advise cloning (copying on of existing samples to new project folder and change as needed)

**Comment by marcikaa78** [comment]
How to create a mp in daEditorX?

**Comment by NicSavichev** [comment]
> How to create a mp in daEditorX?

what is 'mp' ?

**Comment by marcikaa78** [comment]
Sorry it meant to be map

**Comment by NicSavichev** [comment]
> Sorry it meant to be map

As for project, I would suggest using cloning for locations too
Copy whole folder in levels/ for new name and rename *.level.blk to suit new name
