### ISSUE TITLE
ddsx2dds "Oodle read error"

### ISSUE THREAD

**Issue by OshidaBCF** [GaijinEntertainment/DagorEngine#2]
i'm trying to process some DDSX using the ddsx2dds converter in the built release but i'm getting this error
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/06bf339b-a7fa-4be7-9136-d9c19714b5c2)

I have the Oodle dll next to the exe and removing it gives another error
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/598de3de-c369-4781-b4db-1d6a523bebe1)
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/8fd9a408-31d1-40c1-a800-1c1cda1edc3b)
So i guess that it is loading the dll correctly but it's crashing somewhere

Even tho i love programing i never really understand how cmake worked, i tried to built the project from source but i'm missing jam, which require cmake to make

Are we perhaps gonna receive some documentations soon ?

**Comment by AntonYudintsev** [comment]
What ddsx you are processing? where you got it?

**Comment by OshidaBCF** [comment]
This one is one of the new esport skins textures that are available in regional/download_skins.blk

**Comment by NicSavichev** [comment]
> This one is one of the new esport skins textures that are available in regional/download_skins.blk

You cannot unpack textures from WarThunder (downloadable skins/decals) since WarThunder project licenses and uses OODLE compression library and open sourced DagorEngine doesn't have permission to use OODLE, so it is built without it.

**Comment by OshidaBCF** [comment]
> > This one is one of the new esport skins textures that are available in regional/download_skins.blk
> 
> You cannot unpack textures from WarThunder (downloadable skins/decals) since WarThunder project licenses and uses OODLE compression library and open sourced DagorEngine doesn't have permission to use OODLE, so it is built without it.

We have the oodle DLL, see first message screenshot, our tools works "well" but it have some issues on some images and i'm trying to understand why

**Comment by OshidaBCF** [comment]
Fixed via #4
