### ISSUE TITLE
DumpGRP use win32 lib instead of win64

### ISSUE THREAD

**Issue by OshidaBCF** [GaijinEntertainment/DagorEngine#20]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/d93dec34-c649-4436-97f8-7782ce359a10)

For some reason the ioSys/jamfile has Platform equal at win32 and then add oddle's win32 lib instead of the win64, and i cannot find where it's being set

for the time being i just cheated and added `-s Platform=win64 ` to the jam command line in the build_dagor3_cdk_mini.cmd
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/9b529eb0-2d29-431b-8b92-929d57e96727)

For some reason the dumpGrp is the only that's missing

Also i think that the -s aren't supposed to be without a gap after the text
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/a69f94a2-80cc-4cb0-ba2e-33eb809e84a5)

**Comment by NicSavichev** [comment]
> For some reason the dumpGrp is the only that's missing

dumpGrp is built in 32 bit, I will recheck is this intentional (required) or just legacy. If util works (built for win64) then I will change build script

**Comment by OshidaBCF** [comment]
it seems to have built normally forcing 64 bits

It seems to be extracting grp properly so i guess it's okay ?

**Comment by NicSavichev** [comment]
Maybe yes but I remember some issues

**Comment by OshidaBCF** [comment]
i can guess that there will be a very specific case that doesn't work on win 64
