### ISSUE TITLE
[Question] Why does it called daEditorX?

### ISSUE THREAD

**Issue by marcikaa78** [GaijinEntertainment/DagorEngine#26]
And what's different from daEditor3?

**Comment by NicSavichev** [comment]
it is indeed renamed daEditor3, X stands for eXclusive move (in contast with daEditorE lib (formely known as daEditor4) where E stands for Embedded)

**Comment by NicSavichev** [comment]
> And what's this error? (popping up in skiessample and TestGI downloaded the base binaries btw)
> 
> ![Screenshot 2024-01-04 175701](https://private-user-images.githubusercontent.com/132925550/294247541-0ec81bf7-8bfe-4349-9cd1-968be25e7282.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDE2MDAsIm5iZiI6MTcwNDQ0MTMwMCwicGF0aCI6Ii8xMzI5MjU1NTAvMjk0MjQ3NTQxLTBlYzgxYmY3LThiZmUtNDM0OS05Y2QxLTk2OGJlMjVlNzI4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwNzU1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODczNTYzMmIzMGFhNDJjNDhhODgyNzI0ZjU4ZWZkM2RlYzBmY2YyNTA2MzNhYWNkMmE3YmMzMGI1ZjMyMWIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.evENANICm58hT3jCouU_83aqJYSJ22jImjEKdVFv-DA)
> 
> P.S: and how to select/move/rotate objects in editor?, how to modify the editor window name?

Apparently you downloaded base files but didn't build it (using dabuild) into game resources, so game(sample) EXE cannot load  resources on start.
Either download prebuilt archive or build everything needed before running sample

**Comment by marcikaa78** [comment]
Thank you! Ran dabuild and it loads no problem
