### ISSUE TITLE
Building the outerSpace sample / Prebuilt binaries for outerSpace

### ISSUE THREAD

**Issue by Nolram12345** [GaijinEntertainment/DagorEngine#27]
Hello!
Is there any documentation or instructions specifically on how to build the outerSpace sample? Does it require building the entire engine?
Would it be possible to get a pre-built version, like for the other samples?

**Comment by NicSavichev** [comment]
outerSpace is now uploaded only as art source (models, textures, locations), it cannot be built until some new parts of DagorEngine are uploaded to github (this expected to happen nearest 1-2 months).
When source code will be full to allow building then scripts to build and prebuilt binaries will be uploaded as well.

**Comment by Nolram12345** [comment]
Ah, that's good to know. I was a bit confused since there are already scripts to run the game, but running them doesn't work since the binaries are not present.
