### ISSUE TITLE
How to create a landscape

### ISSUE THREAD

**Issue by oschepkovdaniel** [GaijinEntertainment/DagorEngine#28]
Hi! I am currently do some experiments with Dagor Engine. I have built the binaries, and it works fine. However, I am not able to create a landscape in any possible way. When I do Create Heightmap or Import Heightmap, nothing happens. (Well, I mean, technically happens because there is a windows which asks about sizes, etc, and the console says that heightmap was created/imported), but I am not able to see the landscape in any way. even after restarting the editor, or "baking lights". nothing just appears. probably I am doing something wrong.. i guess...

**Comment by NicSavichev** [comment]
What project (sample) do you use to create HMAP?
To show HMAP (both in editor and in game) special shaders must exist.
I think neither skiesSample nor testGI contain this shader so HMAP cannot be created in editor for these projects.
outerSpace (for now asset-only data project) does have shaders for rendering land (and contain GaijaPlanet location sample that uses HMAP)

**Comment by oschepkovdaniel** [comment]
thanks for your answer. so I can use outerSpace to test hmaps right now, or I need to wait when other outerSpace-related files will be uploaded?

**Comment by NicSavichev** [comment]
You can try working with assets and locations. But you cannot use built resources in game unless game source code is published.

**Comment by oschepkovdaniel** [comment]
thanks for your help :D

**Comment by oschepkovdaniel** [comment]
oh, sorry, I have another question. so technically, what I need to copy from outerSpace to my project (which is based on testGI), to be able to use terrain? or is not possible yet too?

**Comment by NicSavichev** [comment]
> oh, sorry, I have another question. so technically, what I need to copy from outerSpace to my project (which is based on testGI), to be able to use terrain? or is not possible yet too?

You cannot use only testGI code. Engine code is enough to load and render HMAP but this code is not present in samples so it will be difficult for you to write it yourself.
Better to wait for more samples (expected this and next month).

**Comment by oschepkovdaniel** [comment]
okay, I understand. thank you
