### ISSUE TITLE
Working with scripts

### ISSUE THREAD

**Issue by oschepkovdaniel** [GaijinEntertainment/DagorEngine#29]
Is there currently any way, to customize game logic. Like, I have created a project, based on testGI, but I was not able to find any examples of "scripts" in samples. Or there is no way currently to customize game's logic right now? The docs are also have not any information about it

**Comment by NicSavichev** [comment]
Currently available samples (physTest, skiesSample, testGI) doesn't use scripts. Their purpose only to check buildability on engine and demonstration of some core render features.
More representative sample is upcoming (it uses DAS (dasclang) scripts and NUT (quirrel) scripts for game logic and UI).
Game UI (daRg-based) scripts can be tested and studied right now with dargbox (part of tools).

**Comment by oschepkovdaniel** [comment]
but does this mean its impossible to use scripts right now (even if i technically figure out how to use it myself), or it requires some additional parts, to be able to run scripts?

**Comment by oschepkovdaniel** [comment]
thanks
