### ISSUE TITLE
How to add new target platform(namely WIndows ARM64)

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#30]
When it comes to 3rd party libraries...Jolt and FMOD have ARM64 support.

**Comment by NicSavichev** [comment]
Right now it would be tricky and will result in something like winarm64 (alongside with win32 and win64).
But I'm going to refactor setup to have Platform = windows linux macOS and PlatformArch = x86 x86_64 arm64 e2k  etc.
This way supporting windows arm64 (as long as linux arm64) will be much easier.

**Comment by CodeLikeCXK** [comment]
> Right now it would be tricky and will result in something like winarm64 (alongside with win32 and win64). But I'm going to refactor setup to have Platform = windows linux macOS and PlatformArch = x86 x86_64 arm64 e2k etc. This way supporting windows arm64 (as long as linux arm64) will be much easier.

I see. How to add a new platform arm64ec in current version(aside with x64,anycpu config setting in solution)

**Comment by NicSavichev** [comment]
Since https://github.com/GaijinEntertainment/DagorEngine/releases/tag/dagor_2024_12_04 you should specify `-sPlatformArch=arm64`
