### ISSUE TITLE
Blender plugin - Equivalent to a Note Track + Keyframes from 3ds Max

### ISSUE THREAD

**Issue by Avarik** [GaijinEntertainment/DagorEngine#31]
Hello. (・ω・｀)
This is mostly a question related to asset exportation to Dagor for War Thunder, I am creating a simple guide for asset exportation to Dagor on both 3ds Max and Blender, and I've discovered that Blender doesn't seem to have something akin to a Note Track with its own keyframes like in 3ds Max.

Without this, it is impossible to export animated assets from Blender to Dagor, only static ones. (Unless you export them to Dagor as is, and then import them to 3ds Max with the Dagor importer for animation purposes)

Do you know if such a function exist and how to use it, or if not is it possible to develop such a function? ε-(´∀｀; )

Thank you! (=´∀｀)人(´∀｀=)
Best regards,
Avarik

**Comment by NicSavichev** [comment]
> Without this, it is impossible to export animated assets from Blender to Dagor, only static ones. (Unless you export them to Dagor as is, and then import them to 3ds Max with the Dagor importer for animation purposes)

I think right now blender plugin is used to export only models, not a2d for animations. But I will find out and will notify what are plans for added animation support to blender exporter.

**Comment by Avarik** [comment]
> > Without this, it is impossible to export animated assets from Blender to Dagor, only static ones. (Unless you export them to Dagor as is, and then import them to 3ds Max with the Dagor importer for animation purposes)
> 
> I think right now blender plugin is used to export only models, not a2d for animations. But I will find out and will notify what are plans for added animation support to blender exporter.

Thank you for the update! Will be wild if it can export animated models too. c:
