### ISSUE TITLE
How to get sources used by some of the includes? 

### ISSUE THREAD

**Issue by wavedao** [GaijinEntertainment/DagorEngine#33]
./DagorEngine-dagor_2024_01_02\prog\gameLibs\publicInclude\dasModules\aotBallistics.h:#include **<gamePhys/ballistics/projectileBallistics.h>**
./DagorEngine-dagor_2024_01_02\prog\gameLibs\publicInclude\dasModules\aotBallistics.h:#include **<gamePhys/ballistics/shellBallistics.h>**

I can't find the 'gamePhys/ballistics' folder in the code base.  Thanks, if someone can point me in the correct direction.

**Comment by NicSavichev** [comment]
They are not published (not needed and will not be published).
I will try to remove references to them

**Comment by Capewearer** [comment]
By the way, there are some Xbox references in code. Should they also be removed?

**Comment by NicSavichev** [comment]
> By the way, there are some Xbox references in code. Should they also be removed?

Unless this reveals any xbox API (names of header files or functions) it not prohibited. If it uses the same API as for windows then it also hardly can be removed.
