### ISSUE TITLE
Blender plugin not working on 4.0?

### ISSUE THREAD

**Issue by Prisoner6278** [GaijinEntertainment/DagorEngine#34]
I installed the plugin on blender(4.0) and I can see that it's been installed but I can't check it to use it for some reason. What am I doing wrong?
![스크린샷(11)](https://github.com/GaijinEntertainment/DagorEngine/assets/84802821/80e034f5-b9bf-41e2-8f8f-fa3e1a8ce94e)

**Comment by Ninkorr** [comment]
Please, add error message from info panel or console. It has to have some kind of feedback on occurring error, when you trying to turn addon on.
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/136897560/a34dbb91-f727-40b4-9a84-413d10392fbe)
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/136897560/45ee78d3-9241-4292-91fb-a8fa05830d50)

**Comment by Prisoner6278** [comment]
Here's the error message.
![스크린샷(19)](https://github.com/GaijinEntertainment/DagorEngine/assets/84802821/ffd9416c-4df0-4273-b59c-6ea1831ee641)

**Comment by Ninkorr** [comment]
I see. It was installed incorrectly. Sources can't be copied directly to addons folder. If you have Python installed - run **pack.bat** or **__build_pack.py**. It creates zip with all necessary files, which can be installed as any other addon from 
**Edit/Preferences/Add-ons/Install**
Alternatively, you can manually copy **pyparsyng.py** and **datablock.py** from **pythonCommon** folder, stored outside of dag4blend sources folder. Just put them into **dag4blend/** directory.

**Comment by Prisoner6278** [comment]
> I see. It was installed incorrectly. Sources can't be copied directly to addons folder. If you have Python installed - run **pack.bat** or **__build_pack.py** (in downloaded sources). It creates zip with all necessary files, which can be installed as any other addon from **Edit/Preferences/Add-ons/Install** Alternatively, you can manually copy **pyparsyng.py** and **datablock.py** from **pythonCommon** folder, stored outside of dag4blend sources folder. Just put them into **dag4blend/** directory.

It worked! Thanks!
