### ISSUE TITLE
Attempting to export the Dag file from the blender results in an error

### ISSUE THREAD

**Issue by vmintf** [GaijinEntertainment/DagorEngine#37]
![issue](https://github.com/GaijinEntertainment/DagorEngine/assets/84371372/3acba30b-4eff-4526-934d-a9246dc58ebb)
I'm getting this error. Is there a way to fix it?

**Comment by Ninkorr** [comment]
Hello. Thanks for report, we're working on fixing it.
For now, you can add Smoothing Groups manually:
- Select all meshes in scene, and choose "Shade Auto Smooth" option from context menu.
- Launch "Preserve Sharp Edges" (N-menu/Tools/Mesh Tools) for same selection
- Go to edit mode, and use "Init" button in Smoothing Groups panel. Currently it works only for active object, so you have to repeat this step for each object... Soon it will be automated once again.

**Comment by vmintf** [comment]
Thank you for your quick response.
I'll try the temporary measure you mentioned.

**Comment by vmintf** [comment]
It's working well. Thanks.

**Comment by vmintf** [comment]
I have one more question besides this. This is off the topic, but is there a way to switch from prefab to dyn model?

**Comment by NicSavichev** [comment]
> I have one more question besides this. This is off the topic, but is there a way to switch from prefab to dyn model?

dynmodel, prefab and rendinst differ only in used shaders for render, as a source it is the same DAG (geometry with materials).
.folder.blk in assets library is used to generate asset of required type (dynmodel or prefab) for given *.dag usually basing on regexp. So we treat *.lod00.dag as first lod of dynModel and simple *.dag as prefab.
More info on asset system here: https://github.com/GaijinEntertainment/DagorEngine/blob/main/assets_docs.md

**Comment by vmintf** [comment]
> > 이 외에도 질문이 하나 더 있습니다. 주제에서 벗어난 내용인데, 프리팹에서 Dyn 모델로 전환할 수 있는 방법이 있나요?
> 
> dynmodel, prefab 및 rendinst는 렌더링에 사용되는 셰이더에서만 다르며 소스는 동일한 DAG(재료가 있는 형상)입니다. 자산 라이브러리의 .folder.blk는 일반적으로 정규 표현식을 기반으로 특정 *.dag에 대해 필요한 유형(dynmodel 또는 prefab)의 자산을 생성하는 데 사용됩니다. 따라서 *.lod00.dag를 dynModel의 첫 번째 lod로 처리하고 간단한 *.dag를 프리팹으로 처리합니다. 자산 시스템에 대한 자세한 내용은 여기를 참조하세요: https://github.com/GaijinEntertainment/DagorEngine/blob/main/assets_docs.md

Thanks to you, I solved it. Thank you.

**Comment by NicSavichev** [comment]
Should be fixed (blender source code in repo and prebuilt ZIP in releases)
