### ISSUE TITLE
Questions about Texture Loads

### ISSUE THREAD

**Issue by vmintf** [GaijinEntertainment/DagorEngine#38]
I'm creating a custom model and I'm posting questions about the texture.

I finished the blk coding and saw this error in the Asset Viewer.
Despite writing the tga file, these errors came up, and I'm asking you a question because I'm wondering exactly how to solve them.

**For your information, I modeled it using a blender.**

![image](https://github.com/GaijinEntertainment/DagorEngine/assets/84371372/ff74db0e-889e-4765-82b1-c4f61a2564a3)

**Comment by NicSavichev** [comment]
.tga extension is ignored (just is reported as is from DAG references in materials) but `su_r_77_rocket_texture` asset is missing in asset base, so asset manager cannot resolve all references needed for dynModel (su_r_rocket asset).
if you just put *.tga to the folder then maybe out default .folder.blk doesn't match .tga extension with regexp.
dabuild handles any texture format (TGA, PNG, JPG, TIFF) but .folder.blk may be setup to match only .tif like
virtual_res_blk{
  find:t="^(.*)\.tif$"
  className:t="tex"
  contents{
    convert:b=yes;fmt:t="DXT1|BC7"
...

**Comment by vmintf** [comment]
It wasn't loading due to different textures, I solved it, thank you.
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/84371372/2c339edf-230f-4938-8282-cd28d7c35b2d)
