### ISSUE TITLE
Failed to build CDK

### ISSUE THREAD

**Issue by JustMinna** [GaijinEntertainment/DagorEngine#4]
Been trying to build the CDK tools but I keep getting an error
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/148638276/1b4b92ef-7df5-4d63-9e7d-bf7ca2ba3f89)

Am I doing something wrong or am I missing something?

**Comment by JustMinna** [comment]
I have no clue how to install it, it seems ancient (literally an MS-DOS application file) and there's not much documentation regarding installation...

**Comment by nikitakrutoy** [comment]
@JustMinna 
You need to build [Gaijin fork of jam](https://github.com/GaijinEntertainment/jam-G8)
[build.vc.cmd](https://github.com/GaijinEntertainment/jam-G8/blob/main/build.vc.cmd) was not working for me for some reason.
I used generated [cmake](https://gist.github.com/nikitakrutoy/979fb597e630ab68fd3c8354d96c4fc1) to build it. Check the VC_DIR and WINKIT_DIR before running.

**Comment by OshidaBCF** [comment]
@nikitakrutoy thanks a lot for the link to the fork

it instantly work but now it say that i don't have FMOD Studio SDK installed, i installed both the "studio" and "API" i found on the website, is the SDK something else ?

**Comment by nikitakrutoy** [comment]
Have you run [make_devtools.py](https://github.com/GaijinEntertainment/DagorEngine/blob/main/make_devtools.py)?

**Comment by JustMinna** [comment]
@nikitakrutoy Yeah and I experience the same issue

**Comment by OshidaBCF** [comment]
Yes i did, i tried to "delete" the folders and redo it after installing both

I may be missing something but it created a lot of folderlinks and all of them have something inside
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/377903e6-3ad9-4073-9855-b4fb3d03edce)

**Comment by nikitakrutoy** [comment]
@OshidaBCF I do not have fmod on my machine, so I can only suggest deleting fmod-studio-2.xx.xx folder and commenting out `if pathlib.Path(fmod_src_folder).exists():`  branch in make_devtools.py.

**Comment by OshidaBCF** [comment]
Make_devtools isn't the one having the error

it's when i do build_all.cmd
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/a0eb6ee1-da04-4686-8f34-7018942c7466)

**Comment by JustMinna** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/148638276/255c6b9a-a6f7-4f3a-81d5-690059e8f97b)
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/148638276/c59c27fb-6797-479c-8ab6-ef792e9efb22)

**Comment by OshidaBCF** [comment]
you need to delete the fmod-studio-2.xx.xx folder and do make_dev.py again

for me those folders and filled with .h, hpp and cpp files

**Comment by JustMinna** [comment]
I did, they are still all empty

**Comment by nikitakrutoy** [comment]
@OshidaBCF I believe you are getting this error because fmod-studio-2.xx.xx is not empty, actually. This is probably a bug. For now, you can solve this by deleting fmod and running make_devtools.py again. Or comment out the code that I described in prev post. This way, the build script will assume that you do not have fmod and would not try to resolve SDK location.

**Comment by OshidaBCF** [comment]
Just tried, doesn't change anything, it's jam that seems to be causing problem

in build_dagor3_cdk_mini.cdk is there is a few lines that are like this

```jam -s Root=../.. -s Platform=win64 -f "path_to_jamfile```

All of them fail with the same error "FMOD Studio SDK not found in please update.

So you think that my jam maybe not be working properly ?

I downloaded the pre built exe from the fork you shared, maybe it's that ?

**Comment by JustMinna** [comment]
When running the build cmd: 
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/148638276/82fb74fa-5d92-498e-895b-cec7e6da4725)

When running the py makedev:
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/148638276/4b47dedb-d1f5-4292-8d95-533652bb153a)

**Comment by OshidaBCF** [comment]
I managed to make build.vc.cmd start

The two arguments are the folder links that the make_dev.py file created

for me it was ```build.vc.cmd C:\WTDHAutomaticEdition\DagorEngine\Build\vc2019_16.10.3 C:\WTDHAutomaticEdition\DagorEngine\Build\win.sdk.100```

Now it cannot find "fcntl.h", it exist in visual inclulde folder, but i don't know how to tell the script "look there if it doesn't have it somehow", then it need std lib which need another ect ect, so i can't just copy all the .h

**Comment by nikitakrutoy** [comment]
@OshidaBCF I had the same issue. That is why is used cmake instead. I tried setting msvc include directories flags in build.vc.cmd at first, but i am not very familiar with msvc, so did not get any results with that.

I doubt that the problem is in jam pre-build executable though. It should work fine too.

**Comment by OshidaBCF** [comment]
Yeah i doubt it's the pre built too
it would be weird for it to "half work"

i know basically nothing about cmake, only that it is a pain to work with.

**Comment by OshidaBCF** [comment]
Found 1 problem : 

in prog\_jBuild\default.jam : l224

the regex pattern is supposed to return 1 slash + the build fault, but it fail if the passed _DEVTOOL variable is only a word, like "Build" in my case

Replacing `MATCH "([^\\\/]*)([\\\/])(.*)"` into `MATCH "([^\\\/]*)(.*)"` now show me a better error than before

Before : 
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/2561243d-7de2-47db-9f2d-74d4df978255)

After : 
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/07f6dd3f-de07-4d0c-b0e8-fd7dec916314)

now it make a little more sense, i'm still searching for the rest of the problem

**Comment by OshidaBCF** [comment]
Found another problem : 

in in prog\\_jBuild\\jBuild.jam : l130

glob isn't given the root folder, so it cannot find the FmodIncPath given
Also the variable point to the element 1 of the array, but the 1 is "core" while 2 is studio
It doesn't really matter because this line is just to see if there is anything in the includes folders

changing `[ GLOB $(FmodIncPath[1]) : * ]` to `[ GLOB $(Root)/$(FmodIncPath[1]) : * ]` Changed the error once again

before : 
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/59cebec3-7ed8-4841-b7d3-d346985140b9)

after : 
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/1c3ec4c1-c35e-472b-baa4-2d06b0bb17b1)

**Comment by OshidaBCF** [comment]
Forget my two previous changes

I found a "more generic" one

In prog/platform.jam, _DEVTOOL is defined by what value you passed to make_devtool.py (Except if the folder i passed happened to be the same as written in the file)

Changing `_DEVTOOL = Build ;` to `_DEVTOOL = $(Root)/Build ;` Fixes a lot of things and it seems to actually be trying to compile the tool

But it's getting a lot of errors now, but seems unrelated to jam, and all of them seems way outside of my capabilities

**Comment by NicSavichev** [comment]
Destination for Devtools folder expected to be absolute path, _DEVTOOL = X:/devtools-gh ; for we

**Comment by OshidaBCF** [comment]
Oh i seee, i gave it a relatif path so it can't work

I should have checked that, but even with the change, i still get a very very large amount of errors
[log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13197420/log.txt)

it seems to be related to cl.exe but i don't know what this exe is supposed to do, seems to be building some .obj

**Comment by OshidaBCF** [comment]
Updated [log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13197494/log.txt) because i noticed it was asking for oodle.dll

cl.exe is still making all the errors

**Comment by NicSavichev** [comment]
do you have MSVC properly installed and have C:\Users\swann\source\repos\DagorEngine\Build\vc2019_16.10.3\bin\Hostx64\x64\cl.exe
EXE here?
OODLE is not relevant (unless you have OODLE license you can build engine and tools without OODLE support, just use ZSTD for packing game resources)

**Comment by NicSavichev** [comment]
> cl.exe is still making all the errors

Did you use jam.exe from https://github.com/GaijinEntertainment/jam-G8/releases/tag/2.5-G8-1.2-2023%2F05%2F04 ?

**Comment by OshidaBCF** [comment]
I'm not sure to have MSVC installed, i have VC2022 but not 2019 so this might cause issues

I use the jam.exe from the fork and it works no problem

I just checked and C:\Users\swann\source\repos\DagorEngine\Build\vc2019_16.10.3\bin doesn't even exist, i guess i really need vc 2019

**Comment by OshidaBCF** [comment]
I tried to run the py script again and it say that the simlink is created
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/3455324f-b2d3-4a3c-a011-d332d5324005)

it linked to `C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC` but there is no "bin" folder inside, so i don't have MSVC installed

**Comment by NicSavichev** [comment]
2019, x64/x86
maybe 2015 is also needed (since it stay default now), but you have to use previous buildtools installer)

**Comment by OshidaBCF** [comment]
Ah oups...

**Comment by NicSavichev** [comment]
also be warned to use english locale for VC (or it will cannot manage dependencies)
I'm currently working on update (to handle any locale, not english one) but latest version on github requires this

**Comment by OshidaBCF** [comment]
i installed MSVC and now it's building

that is a lot of includes

**Comment by NicSavichev** [comment]
> that is a lot of includes

something "note: including ..." in non-english locale?
it is wrong behaviour, output filter should capture these lines and redirect to deps files
if you see these lines it failed to capture

**Comment by OshidaBCF** [comment]
i see i was wondering what you meant by "use english locale for VC"

do i need to change the language of VS ?

**Comment by NicSavichev** [comment]
> do i need to change the language of VS ?

I think yes, please

**Comment by OshidaBCF** [comment]
I tried changing Visual Studio's language to "english", and it is in english, but i still get the "note including..."

**Comment by OshidaBCF** [comment]
i can try to uninstall the french language pack

**Comment by OshidaBCF** [comment]
Ah it's "working"

i get less errors, but no "note including"

**Comment by OshidaBCF** [comment]
while my cpu is screaming building the cdk, i can't stop wondering why the build couldn't work in french, it's not like it was a different platform right ?

**Comment by OshidaBCF** [comment]
[log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13197887/log.txt)

i didn't excpeted to have that little errors

**Comment by NicSavichev** [comment]
I think it is not compiler we used to use
do you compile with VC2022?
C:\Users\swann\source\repos\DagorEngine\prog\dagorInclude\math/dag_Point3.h(31): error C2220: the following warning is treated as an error
C:\Users\swann\source\repos\DagorEngine\prog\dagorInclude\math/dag_Point3.h(31): warning C5267: definition of implicit assignment operator for 'Point3' is deprecated because it has a user-provided copy constructor
C:\Users\swann\source\repos\DagorEngine\prog\dagorInclude\math/dag_Point3.h(31): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings

**Comment by NicSavichev** [comment]
try adding locally
+++ b/prog/_jBuild/win64/vc16-sets.jam
@@ -26,4 +26,5 @@ local _DEF_C_CMDLINE =
   /c /nologo /Zc:forScope /Zp8 /J
   /Zc:inline /bigobj
+  /Wv:18
 ;
to X:\github\DagorEngine.git\prog\_jBuild\win64\vc16-sets.jam

**Comment by OshidaBCF** [comment]
Frankly i have no idea, what i have should be Visual Studio Community 2022
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/f9d640c9-b04f-4656-946f-3f7bd5929994)

The versioning of visual tools is hard to keep up with

**Comment by OshidaBCF** [comment]
It seems to be buildign everything that didn't build before without issue

Also i switched the VS Installer language to english, so it should be easier to know what module i really need

**Comment by OshidaBCF** [comment]
[log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13197999/log.txt)

Got way less errors, but still some

**Comment by NicSavichev** [comment]
how come you get
..\..\prog\engine\ioSys\oodleIo.cpp(7): fatal error C1083: Cannot open include file: 'oodle2.h': No such file or directory
instead of
OODLE is missing, ignored 
?
did you added empty folder to devtools manually? remove it then

**Comment by OshidaBCF** [comment]
i added a "oodle.2.7" folder with the dll inside to remove the error from before

i forgot that i didn't really needed it, i removed it and rerun the build without deleting the _output folder, tell me if i should delete it before rebuilding.
[log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13198109/log.txt)

**Comment by OshidaBCF** [comment]
Also i disabled the rerun of the build script if it failed, should i enable it back ?

**Comment by OshidaBCF** [comment]
[log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13198197/log.txt)

re tried with deleteing the folder, it seems i only got errors about "atomic" and dav1d's lib

**Comment by NicSavichev** [comment]
> [log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13198197/log.txt)
> 
> re tried with deleteing the folder, it seems i only got errors about "atomic" and dav1d's lib

I'm rechecking on clean machine (with just installed VC tools)
Are you sure script made proper symlinks to vc2019? It was reported that it may symlink to vc2022 instead if it is available
I will recheck now whether code is buildable with recent vc2019 (last installed was 19.20.30148 this spring)

**Comment by OshidaBCF** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/e383a3b3-976b-477b-b32e-f0fbbba870d0)
i created a random file in the bin inside the simlink to find where it was, and it seem to use vc2022

the py code that make link open the path `Program Files (x86)\Microsoft Visual Studio\2022\BuildTools` so it make sense that i would take 22 no ?

Am i mixing up names again ?

**Comment by NicSavichev** [comment]
> ![image](https://user-images.githubusercontent.com/61458287/278875368-e383a3b3-976b-477b-b32e-f0fbbba870d0.png) i created a random file in the bin inside the simlink to find where it was, and it seem to use vc2022
> 
> the py code that make link open the path `Program Files (x86)\Microsoft Visual Studio\2022\BuildTools` so it make sense that i would take 22 no ?
> 
> Am i mixing up names again ?

Yes, change symlink manually to 2019.
We will fix script later to avoid this bug

**Comment by OshidaBCF** [comment]
i don't have any "2019" folder next to the 2022, i guess i would need to install VS 2019

I'm not sure how to edit symlink, should i just modify the pyscript, and run it again after deleting the folder ?

**Comment by OshidaBCF** [comment]
[log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13198383/log.txt)

I got some external help to install VCR2019, after redoing the symlink, this is what the build did.

It seems to have managed to build Dav1d's lib

Now it's having some error on what looks to be previously build files, so i guess i should rebuild from scratch

**Comment by NicSavichev** [comment]
> Now it's having some error on what looks to be previously build files, so i guess i should rebuild from scratch

Yes, this is true.
jam tries to check dependences as much as possible but it doesn't handle case when changing compiler for the same output
PDB will likely fail

**Comment by OshidaBCF** [comment]
I mean that does make some sense, if the file is already there it's a good guess that it was just already built before

Right now i'm recompiling and it seems to have no error... yet

**Comment by OshidaBCF** [comment]
After 2 hours, building finally finished, how long does it usually take you ?
[log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13198634/log.txt)

i think i got a few errors about "shaders", but otherwise everything should be alright

**Comment by NicSavichev** [comment]
> After 2 hours, building finally finished, how long does it usually take you ? [log.txt]

compilation takes 30 min (but I use 36-cores i9)

**Comment by OshidaBCF** [comment]
Yeah i have a 8 core R7

sadly this didn't helped me fix my problem mentioned in #2 

I couldn't find in the files a reason why oodle wouldn't open

**Comment by NicSavichev** [comment]
> I couldn't find in the files a reason why oodle wouldn't open

what Oodle do you have? we use 2.9.2 for runtime (game and unpack) and 2.7.6 for packing in tools (hold older version to avoid updating 50Gb of texture packs)
if Oodle is linked then tools should be able to unpack them
did you try ddsx2dds with -dump option to see header's dump?

**Comment by OshidaBCF** [comment]
-dump works
and -check:OODLE also work

As for the Oodle version, i have no idea the only thing i have is the name, `oo2core_6_win64.dll`

it works with the previous tool i had so it should work with this one


how do i link the dll ?

**Comment by NicSavichev** [comment]
> how do i link the dll ?

I don't think it is possible since we use static libs
    case win32 : AddLibs += $(oodle_dir)/static_lib/oo2core_win32.lib ;
    case win64 : AddLibs += $(oodle_dir)/static_lib/oo2core_win64.lib ;
If you do have license for OODLE then you have these headers and libs
C:\devtools\oodle.2.9\include\oodle2.h
C:\devtools\oodle.2.9\include\oodle2base.h
C:\devtools\oodle.2.9\include\oodle2x.hC:\devtools\oodle.2.9\static_lib\oo2core_win32.lib
C:\devtools\oodle.2.9\static_lib\oo2core_win32_debug.lib
C:\devtools\oodle.2.9\static_lib\oo2core_win64.lib
C:\devtools\oodle.2.9\static_lib\oo2core_win64_debug.lib
and import libs must be located here
C:\devtools\oodle.2.9\lib\oo2core_win32.lib
C:\devtools\oodle.2.9\lib\oo2core_win64.lib
but you should change prog/engine/ioSys/jamfile too in order to link import libs instead of static ones

**Comment by OshidaBCF** [comment]
right now i only have the dll, but i'll try to aquire the lib.

if i can get the lib, do i just put in a folder in the "build folder" ?

like Build/oodle.2.7.oo2core_win_64.lib ?

**Comment by NicSavichev** [comment]
> As for the Oodle version, i have no idea the only thing i have is the name, `oo2core_6_win64.dll`
also I suspect this name means Oodle ver 2.6.x
and it may be just incompatible with 2.7.6 that we use for packing
you need newer lib anyway

**Comment by OshidaBCF** [comment]
i see....

well if i can find a lib i can probably find newer

**Comment by NicSavichev** [comment]
> well if i can find a lib i can probably find newer

I need lib anyway, static one or import one
you cannot use DLL without any lib (import libs loads that DLL and resolves symbols)

**Comment by OshidaBCF** [comment]
oh god... it's starting to get quite complicated

**Comment by OshidaBCF** [comment]
i found a lib, that was easier than expected, 3 month old so it should be fine no ?

**Comment by OshidaBCF** [comment]
> case win64 : AddLibs += $(oodle_dir)/static_lib/oo2core_win64.lib ;

Do i just have to do that an rebuild the tool ?
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/2dc4c922-1f4d-4792-91a3-c4e06b90e330)

**Comment by NicSavichev** [comment]
> Do i just have to do that an rebuild the tool ? ![image](https://user-images.githubusercontent.com/61458287/278892235-
yes, run
X:\github\DagorEngine.git\prog\tools\build_dagor3_cdk_mini.cmd
or
jam in X:\github\DagorEngine.git\prog\tools\converters\ddsx2dds\

**Comment by OshidaBCF** [comment]
Oh yeah i guess that now that it can find the lib it'll build it

**Comment by OshidaBCF** [comment]
[log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13198993/log.txt)

It build some new files but still failed because it couldn't find all the headers and things (i forgot to log the first build)

**Comment by NicSavichev** [comment]
> [log.txt](https://github.com/GaijinEntertainment/DagorEngine/files/13198993/log.txt)
> 
> It build some new files but still failed because it couldn't find all the headers and things (i forgot to log the first build)

you need ...\build\oodle.2.7\include\oodle2.h to compile

**Comment by NicSavichev** [comment]
also you can use `jam -dx`  to see actual commandline (so you know what folders are added for includes, etc.)

**Comment by OshidaBCF** [comment]
IT WORKEDDDDDDDDDDDDDDDDDDDD

HAHAHAHAHAHAHA

**Comment by OshidaBCF** [comment]
Thanks a lot <3

**Comment by NicSavichev** [comment]
> @JustMinna You need to build [Gaijin fork of jam](https://github.com/GaijinEntertainment/jam-G8) [build.vc.cmd](https://github.com/GaijinEntertainment/jam-G8/blob/main/build.vc.cmd) was not working for me for some reason. I used generated [cmake](https://gist.github.com/nikitakrutoy/979fb597e630ab68fd3c8354d96c4fc1) to build it. Check the VC_DIR and WINKIT_DIR before running.

You don't need to build 'jam' at all, get EXE from releases https://github.com/GaijinEntertainment/jam-G8/releases/download/2.5-G8-1.2-2023%2F05%2F04/jam-win64.zip
just unpack it to any folder that exists in PATHs

**Comment by JustMinna** [comment]
Alrighty, thanks

**Comment by JustMinna** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/148638276/b1020d2e-d1b1-4fbb-a325-95dfdb406a33)
Did you find a fix for this issue?

**Comment by JustMinna** [comment]
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/148638276/0cad7380-60d7-48b9-bc0d-22403f81be1b)
However I'm having another issue... I can probably download this dll from somewhere though... I assume

**Comment by NicSavichev** [comment]
> ![image](https://user-images.githubusercontent.com/148638276/279189146-0cad7380-60d7-48b9-bc0d-22403f81be1b.png) However I'm having another issue... I can probably download this dll from somewhere though... I assume

This DLL (as well as many other important files) are located in tools-base.7z (downloadable from releases) and that these files must be unpacked to repo folder before building and using built tools

**Comment by OshidaBCF** [comment]
I had it downloaded and copied the PVRTexLib, it could launch but then crashed because of shaders not being compiled

**Comment by NicSavichev** [comment]
> now i understand why i should have merged the two folder, the building override the exes right ?
Yes, initially we combine GIT repo + 2 unpacked base archives (refer to newly added [README.md](https://github.com/GaijinEntertainment/DagorEngine/blob/main/README.md) for details).
Then we build tools (build_dagor3_cdk_mini.cmd) and samples (EXE with jam, shaders with compile_shaders_*.bat and game resources with dabuild.cmd; sometimes we need to build pre-rasterized fonts). After building these (it is development pipeline) we can run samples.

Instead of building tools you can download and unpack [tools-prebuilt.7z](https://github.com/GaijinEntertainment/DagorEngine/releases/download/dagor_2023_10_31/tools-prebuilt.7z)
Instead of building samples you can download prebuilt data and EXE [samples-prebuilt-game.7z](https://github.com/GaijinEntertainment/DagorEngine/releases/download/dagor_2023_10_31/samples-prebuilt-game.7z)
Rebuilding EXE is easiest part of build pipeline.

**Comment by OshidaBCF** [comment]
I see that a lot of files changed

Should i delete everything and redo everything from 0 ?

**Comment by OshidaBCF** [comment]
Well i was curious and have time to spend, so i just redid everything from scratch

The py script seems to have removed a couple of elements from my Path variable, a few programs (jam included) couldn't be called anymore

**Comment by NicSavichev** [comment]
> The py script seems to have removed a couple of elements from my Path variable, a few programs (jam included) couldn't be called anymore

Really strange, when I tested it script downloaded jam to root of devtools folder and asked to add devtools folder to the paths (but I never tried to confirm adding)

**Comment by OshidaBCF** [comment]
i had jam.exe on my pc from yesterday, the py script didn't download jam at all

Maybe it checked if i had jam and noticed i did ?

**Comment by NicSavichev** [comment]
> Maybe it checked if i had jam and noticed i did ?

it searches jam.exe in PATH folders and skips installing if found

**Comment by OshidaBCF** [comment]
then perhaps it found it and overwrote everything after it + a few lines before.

When i opened the path, the last line onlt had "C:/P" inside
probably the start of C:/Program x86

**Comment by NicSavichev** [comment]
> When i opened the path, the last line onlt had "C:/P" inside probably the start of C:/Program x86

Don't use folders with spaces in name when dealing with jam. This wil cause awful headache

**Comment by OshidaBCF** [comment]
it's just the translation, iirc the actual folder doesn't have spaces.

**Comment by OshidaBCF** [comment]
> Well i was curious and have time to spend, so i just redid everything from scratch
> 
> The py script seems to have removed a couple of elements from my Path variable, a few programs (jam included) couldn't be called anymore

It seems that this was actually caused by my global Path variable being too long, after starting my computer this morning, a few lines have been removed again

**Comment by NicSavichev** [comment]
> It seems that this was actually caused by my global Path variable being too long, after starting my computer this morning, a few lines have been removed again

[fixed script](https://github.com/GaijinEntertainment/DagorEngine/commit/1310ed1b7b3429b2116b973769f0fe52153008ba)
