### ISSUE TITLE
[Question] Is there a project creation feature?

### ISSUE THREAD

**Issue by reityerukohaku2** [GaijinEntertainment/DagorEngine#42]
Is there a function to create a new project in daEditor, etc.?
Or is the only way to create a project manually?

**Comment by NicSavichev** [comment]
> Is there a function to create a new project in daEditor, etc.? Or is the only way to create a project manually?

Right now - only by cloning. Copy project folder to new name, update *.level.blk and open location in daEditor.
The same holds for whole project (that contains application.blk setup)
