### ISSUE TITLE
Repo/Releases update

### ISSUE THREAD

**Issue by marcikaa78** [GaijinEntertainment/DagorEngine#46]
When will be an update to the repo? We didn't got updates since 3months ago. @NicSavichev

**Comment by NicSavichev** [comment]
I expect it soon, I'm still preparing new code for release.

**Comment by marcikaa78** [comment]
Will there be an FPS template?

**Comment by NicSavichev** [comment]
I expect TPS sample being added (but it can be easily changed to FPS camera)

**Comment by marcikaa78** [comment]
ah, ok thank you
