### ISSUE TITLE
What is dagor6 and dagor4 in the commits?

### ISSUE THREAD

**Issue by marcikaa78** [GaijinEntertainment/DagorEngine#47]
I just saw these 2 in the commits nooow im a little bit confused what dagor version is this repo.

**Comment by NicSavichev** [comment]
> If WT or Enlisted, CRSED uses Physx obviously.

Non of them use PhysX (besides small part of WT for destructible objects that uses older PhysX Apex lib)

**Comment by marcikaa78** [comment]
I thought all Gaijin games were usinng Havok lol

**Comment by marcikaa78** [comment]
And is DaRG JS,HTML or C++

**Comment by NicSavichev** [comment]
daRG is quirrel-script based ( https://github.com/GaijinEntertainment/quirrel )

**Comment by marcikaa78** [comment]
How to make a DaRG UI show up when you launch the sample/game

**Comment by NicSavichev** [comment]
Currently uploaded samples don't use daRG (I mean, physTest, skiesSample, testGI), so you can see and test daRG snippets only in dargBox (built with other tools).
New upcoming sample will have some daRG UI but I think it is subtle (key hints and in-game menu of 2 items - Continue and Quit)

**Comment by marcikaa78** [comment]
when will a new release happen?
