### ISSUE TITLE
How to port OuterSpace level and assets to GItest?

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#48]
Also how to switch level in console?

**Comment by NicSavichev** [comment]
Do you mean reload another location in testGI? I think it is not implemented, location and such data is loaded once on start in this sample.

**Comment by CodeLikeCXK** [comment]
> Do you mean reload another location in testGI? I think it is not implemented, location and such data is loaded once on start in this sample.

I mean copy levels and assets from OuterSpace to testGI, build them and open it,
As far as I know the level is set in settings.blk and I have changed the level from sponza to walkpoly

**Comment by NicSavichev** [comment]
testGI sample cannot load locations like OuterSpace's ones, so just use OuterSpace game sample to load it.
Available since https://github.com/GaijinEntertainment/DagorEngine/releases/tag/dagor_2024_12_04
