### ISSUE TITLE
Possible light bleeding.

### ISSUE THREAD

**Issue by Capewearer** [GaijinEntertainment/DagorEngine#57]
These two screenshots in Sponza Demo (testGI) show that light on the common edge of wall and floor has tendency to disappear when camera moves closer. Maybe that's because shadow rendering distance is low (I don't know how to change that, haven't found in ImGUI right option).
![изображение](https://github.com/GaijinEntertainment/DagorEngine/assets/145611338/50124cb4-ef7d-4665-a35d-a67165cf4809)
![изображение](https://github.com/GaijinEntertainment/DagorEngine/assets/145611338/07445b56-6f59-4b49-bd8f-7a6ff4647a0f)
Hardware: Intel i3-4130 (2 cores 3.4 GHz), AMD R7 260X, 6 Gb RAM. Testing has been done on Windows 7.

**Comment by moleium** [comment]
There are graphics & rendering settings in the blk of the example. it's probably there

**Comment by AntonYudintsev** [comment]
Has been fixed with DaGI2
