### ISSUE TITLE
OpenGL driver? 

### ISSUE THREAD

**Issue by MetalMaxMX** [GaijinEntertainment/DagorEngine#65]
Hello! 

I was wondering something. But is it possible for the engine to support a driver that has OpenGL support? I was just checking and it seems like it already supports DirectX11. So perhaps something like OpenGL 3.3 or even 4.6 is not out of the realm of possibility? 

Just asking. 

The best,
MetalMaxMX.

**Comment by NicSavichev** [comment]
We have dropped support for both OpenGL3 and OpenGLES3 more than 3 years ago (in favor of Metal on macOS/iOS and Vulkan on linux/android). Potentially you can write it anew but I think d3d API of DagorEngine cannot be fully implemented using OpenGL.
Also you will need GLSL shader compiler (that was removed 2 years ago).
So I think trying to restore OpenGL support is impractical (
