### ISSUE TITLE
Could benchmark of many lights be added?

### ISSUE THREAD

**Issue by Capewearer** [GaijinEntertainment/DagorEngine#66]
Dagor engine uses clustered deferred shading, so it would be reasonable to show high limits of realtime lighting. Especially interesting is the case with many shadow-casting lights.

**Comment by AntonYudintsev** [comment]
Both dngSceneViewer
[dngSceneViewer](https://github.com/GaijinEntertainment/DagorEngine/tree/main/samples/dngSceneViewer/prog)
and testGI samples now have (many) lights used, all of which are shadow casting.
Also, in dngSceneViewer clustered lights are only used for transparent / volumetrics, and tiled lights are used for opaque (gbuffer resolve)
