### ISSUE TITLE
Dag4Blend: auto_smooth_angle has been removed in Blender 4.1+, and making export impossible

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#69]
How to solve it?
![597b7011d8e118f68b786d52219cb3e8](https://github.com/GaijinEntertainment/DagorEngine/assets/44729188/c01c23d1-760c-4cf0-a242-48ae551ae568)
![b90d39b8d79691b552d43833fde304af](https://github.com/GaijinEntertainment/DagorEngine/assets/44729188/727fad81-fa71-48fc-8cbe-7a125a13ce7a)
![bb99ba1d8341b1132471863751f4c87c](https://github.com/GaijinEntertainment/DagorEngine/assets/44729188/448463a1-8420-48d0-bf4e-c8861e3aa915)

**Comment by NicSavichev** [comment]
Try updated version https://github.com/GaijinEntertainment/DagorEngine/commit/c7824cf69a01bfa46753447a812aed3b60c0e9f5

**Comment by CodeLikeCXK** [comment]
> Try updated version [c7824cf](https://github.com/GaijinEntertainment/DagorEngine/commit/c7824cf69a01bfa46753447a812aed3b60c0e9f5)

I have checked that. The export works now, but is there anyway to convert all default material to certain type of dagmat like those in 3dsmax?
