### ISSUE TITLE
GPU Incompatibility

### ISSUE THREAD

**Issue by Jxqal** [GaijinEntertainment/DagorEngine#7]
When i start the editor, everything seems to work. but when selecting the Skies Sample for example, im getting multiple errors. They look like this:
![Screenshot 2023-11-01 155507](https://github.com/GaijinEntertainment/DagorEngine/assets/115593280/e15bfd59-33a7-4b0c-93a2-63fefbc3e62c). I have an RTX 2060, so i cant find a reason for it to give me those errors.

**Comment by AntonYudintsev** [comment]
You have no prebuilt tools shader in a game folder

**Comment by Jxqal** [comment]
> You have no prebuilt tools shader in a game folder

And how do i get those? Do i have to Download Something additionally? I used the Sample Files, but the Same error applies to them.

**Comment by NicSavichev** [comment]
> And how do i get those? Do i have to Download Something additionally? I used the Sample Files, but the Same error applies to them.

run samples\skiesSample\prog\shaders\compile_shaders_tools.bat or samples\testGI\prog\shaders\compile_shaders_tools.bat
this will create
...\tools\common\compiledShaders\tools.exp.ps50.shdump.bin
...\tools\common\compiledShaders\tools.ps50.shdump.bin
files that are used for tools and for building assets

**Comment by Nolram12345** [comment]
Using those scripts always results in the shader compiler being unable to open the BLK shader compile config files with errors like these:
`[FATAL ERROR] Cannot open BLK file '.\shaders_pc11.blk' (file not found or syntax error, see log for details)
Dagor Shader Compiler 2.72 (dump format '  11', obj format '10.9', shader cache ver 0x5)
Target: PC DirectX 11, SDK.47`

Even though those very BLK files are located in the exact directory of the batch file.

**Comment by OshidaBCF** [comment]
Even after building the shaders i get this when launching AssetViewer
![image](https://github.com/GaijinEntertainment/DagorEngine/assets/61458287/91f16dd8-b52b-45e9-9d07-209667856215)

**Comment by mastermindsm** [comment]
[SMM Instagram](https://smmperfect.com/) involves using strategic social media marketing techniques to enhance brand visibility, engage with the target audience, and promote products or services on the platform.

**Comment by NicSavichev** [comment]
> Even after building the shaders i get this when launching AssetViewer

Shaders dump format is not fixed and may change. Apparently shaders dump from WT CDK (which matches WT production version) differ from latest shader dump format on github

**Comment by OshidaBCF** [comment]
I see.
