### ISSUE TITLE
Issues installing the Dagor editor from Github

### ISSUE THREAD

**Issue by Izzy1665** [GaijinEntertainment/DagorEngine#71]
I've downloaded the DagorEngine-main file from Github, followed all the instructions and am at the point where the deveop\devtools file is crearted. Problem here is that when the script is run it does not create all the entries in the devtools folder that the instructions say will be created. I've rerun the script several times and get the same result each time. I am not sure where to go from here. HELP !

To be loaded
![devtools_to_be_loaded](https://github.com/user-attachments/assets/cee0d5f0-5975-4874-8644-ae5e4d7d3992)

Actually loaded
![dev_tools_actually_loaded](https://github.com/user-attachments/assets/9499867b-7929-4952-b4b3-0386ea5d80e9)

**Comment by NicSavichev** [comment]
Apperently script stopped before end. Log of script execution would be handy in this case.
For me scripts (windows/macOS/linux) work properly on every machine where I start them
