### ISSUE TITLE
Removing degenerate after editing mesh in 3dsmax 2016 would freeze 3dsmax for more than 2 hours

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#72]
steps:
1. Import obj as editable polygon
2. Remove several faces of polygon
3. Convert to editable mesh
4. Click remove degenrate in Dagor Utility
5. 3dsmax freeze
Not sure if the plugin is working normally

**Comment by NicSavichev** [comment]
Try rechecking with recent build of plugins, that bug is supposed to be fixed some time ago

**Comment by CodeLikeCXK** [comment]
I see. Thanks!
