### ISSUE TITLE
Confusing line when setting window resolution

### ISSUE THREAD

**Issue by fluffyball9** [GaijinEntertainment/DagorEngine#75]
In `prog/engine/drv/drv3d_commonCode/drv_utils.cpp`, line 206 reads:

`src_wdt = min(scr_hgt * base_scr_wdt / base_scr_hgt, base_scr_wdt);`

I'm trying to understand this; if the goal is to force the aspect ratio to be the same, then why is there a comparison between the corrected scr_wdt and base_scr_wdt?

The main reason I'm asking is because this means that the window won't upscale horizontally.

**Comment by NicSavichev** [comment]
original message for this line sounds as `fixed full screen windowed mode when changing a resolution from the ingame menu`
`also fixed bug in which viewport could occupy a small part of the window after switching from fullscreen to windowed mode`
I think it should maintain aspect ratio but need some sample to test on
