### ISSUE TITLE
 crypto.lib lld-link error

### ISSUE THREAD

**Issue by cwycn** [GaijinEntertainment/DagorEngine#8]
by the way, thanks for  open source the great engine 

run build_all, all other is ok but

...found 10435 target(s)...
...updating 2 target(s)...
creating lib crypto.lib
@C:\Users\ADMINI~1\AppData\Local\Temp\jam: no such file or directory
lld-link: error: lib failed
----------------------------------------------------------------------
FAILED to build crypto.lib [Error #1] [win64~100~clang~15.0.7~dev~m~s4~ex~nosp]
.

...failed lib_target ../../../_output/win64~100~clang~15.0.7~dev~m~s4~ex~nosp/3rdPartyLibs/openssl_3_x/crypto.lib ...
...skipped ../../../samples/testGI/prog/../game/testGI-win64-dev.exe for lack of ../../../_output/win64~100~clang~15.0.7~dev~m~s4~ex~nosp/3rdPartyLibs/openssl_3_x/crypto.lib...
...failed updating 1 target(s)...
...skipped 1 target(s)...

and  
change samples\skiesSample\prog\jamfile
PlatformSpec ?= clang; to
PlatformSpec ?= vc16 ;
it  build  samples exe  but  not for clang because clang crypto.lib failed link
i can't find reason , have any idea ?

**Comment by NicSavichev** [comment]
> and change samples\skiesSample\prog\jamfile PlatformSpec ?= clang; to PlatformSpec ?= vc16 ; it build samples exe but not for clang because clang crypto.lib failed link i can't find reason , have any idea ?

yes. probem is full pathname of files that are written during compilation
avoid using root folder (where DagorEngine lies) with too long pathname of spaces

**Comment by NicSavichev** [comment]
also antivirus (windows defender) may interfere compilation, when we write response file to temp folder and then read back it with compiler/linker/lib - file may be blocked by antivirus and this fails compilation

**Comment by cwycn** [comment]
ok, got it,thanks
