### ISSUE TITLE
Failed to open exported scene: How does that happen?

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#81]
![image](https://github.com/user-attachments/assets/2b854bfa-a7be-43ca-91f1-016941bd9434)

While exporting from DaEditor, various max limit including texture numbers are met. After rising them in application.blk, the map could be exported, but not able to open in testGI.
How to solve that?

**Comment by NicSavichev** [comment]
DagorEngine.git\samples\testGI\prog\test_app.cpp  2372
  ::enable_tex_mgr_mt(true, 1024);
change this line with more entries (you can easily change it to (32<<10) at once)
it is needed for preallocating arrays of resMgr (so entries can be added from different threads without reallocation of arrays)

**Comment by CodeLikeCXK** [comment]
> DagorEngine.git\samples\testGI\prog\test_app.cpp 2372 ::enable_tex_mgr_mt(true, 1024); change this line with more entries (you can easily change it to (32<<10) at once) it is needed for preallocating arrays of resMgr (so entries can be added from different threads without reallocation of arrays)

I see. Now I can open it. Thanks! Also, how to tweak shadow distance and quality? For large scene is there any way to optimize?
![1c5e1cbe23ecadb72d453535446dc853](https://github.com/user-attachments/assets/8e04c80d-f15f-4b87-bc69-974affca49bd)
