### ISSUE TITLE
Console Verification Process?

### ISSUE THREAD

**Issue by JailbreakPapa** [GaijinEntertainment/DagorEngine#86]
Hello,

Is there currently a process for gaining access to console builds for Dagor (namely Xbox Platforms & PS4/5)?

**Comment by NicSavichev** [comment]
No.

**Comment by JailbreakPapa** [comment]
@NicSavichev just want to make sure on this, will there ever be a process for this, or will approved developers just have to port it themselves to the respective platforms?

**Comment by AntonYudintsev** [comment]
We need to obtain “middleware status” from platformholders. It is doable, but we haven’t done that yet.

when we will, you would have to use standard procedures for the platforms to verify your developer status for a platform and obtain an access to platform-specific code. 

If it become a pressing issue before that, we can be “co-developer” for a specific project (and provide nessesary code).

**Comment by JailbreakPapa** [comment]
> We need to obtain “middleware status” from platformholders. It is doable, but we haven’t done that yet.
> 
> when we will, you would have to use standard procedures for the platforms to verify your developer status for a platform and obtain an access to platform-specific code.
> 
> If it become a pressing issue before that, we can be “co-developer” for a specific project (and provide nessesary code).

No problem, once you guys are registered, please make sure to make announcement, so me and other console developers can just check with the respective platform holders on confirming our status.
