### ISSUE TITLE
Trying to compile GITest sample for windows arm64 and runs into error while compiling drv3d_DX12

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#88]
How to compile the sample without drv3d_DX12(dx11 only and drv3d_DX11 is ready) since it's the only error stopping the build, or how to fix this error?
![image](https://github.com/user-attachments/assets/00d97946-d47f-4d51-bd92-7209448bcbbc)
![image](https://github.com/user-attachments/assets/5bc070ad-57a8-43e7-bd48-11d3e4f60689)
![image](https://github.com/user-attachments/assets/c601b749-06c5-42f5-8946-b05318a9ca1a)

**Comment by NicSavichev** [comment]
just update jamfile similar to this
+++ b/samples/testGI/prog/jamfile
@@ -7,4 +7,5 @@ Location = samples/testGI/prog ;
 
 UseD3DMulti ?= yes ;
+UseD3DMultiList = stub DX11 ;

**Comment by NicSavichev** [comment]
if you build for arm64 (windows-on-arm64) as I see in your log better use VC instead of clang
Change jamfile like
+++ b/samples/testGI/prog/jamfile
@@ -1,5 +1,6 @@
 #Platform ?= macOS ;
 PlatformArch_windows ?= x86_64 ;
-PlatformSpec_windows ?= clang ;
+PlatformSpec_windows_x86_64 ?= clang ;
+PlatformSpec_windows_arm64 ?= vc17 ;

or just build with explicit jam -sPlatformArch=arm64 -sPlatformSpec=vc17
both vc2019_16.11.34 vc2022_17.9.5 handle arm64 better than clang-15.0.7.

**Comment by NicSavichev** [comment]
For arm64 I advise using DX12 as for my experience hardware with arm64 has poor support for DX11 (in drivers).
Our big game built for arm64 run on DX12 normally but crash randomly on DX11 (at least on MS minipc)

**Comment by NicSavichev** [comment]
though I just tested - drv3d_dx12 compiles for me even with clang 15.0.7
SUCCESSFULLY built testGI-win-arm64-dev.exe  [windows-100~arm64~dev~clang-15.0.7~m~s2~ex]
maybe you skipped updating devtools to actual used toolchains with make_devtools.py ?

**Comment by CodeLikeCXK** [comment]
> +PlatformSpec_windows_x86_64 ?= clang ;
> +PlatformSpec_windows_arm64 ?= vc17 ;

Thanks! I have updated llvm to latest native version to use the clang native version.
Tookchains are updated too.
The testGI sample can be compiled through these methods now(the cl.exe is still arm64 though). The shaders are absent so I need to find a way to compile shaders. I would try if I could compile engine tools in the same way and use native arm64 toolchain to compile it. Thanks!

**Comment by CodeLikeCXK** [comment]
> though I just tested - drv3d_dx12 compiles for me even with clang 15.0.7 `SUCCESSFULLY built testGI-win-arm64-dev.exe [windows-100~arm64~dev~clang-15.0.7~m~s2~ex]` maybe you skipped updating devtools to actual used toolchains with make_devtools.py ?

![image](https://github.com/user-attachments/assets/98c4a2e3-d829-4e00-b2a1-6661d8e70d3b)
The testGI sample now runs natively. However it can't use dx12 driver even if  driver:t="dx12" is set in setting. Also the shader compiler executable for dx12 is absent(only dx11 is available). How would that happen?
![image](https://github.com/user-attachments/assets/d7c01183-d4b4-4c09-803a-94b043ee0030)

**Comment by NicSavichev** [comment]
I didn't try to build tools for native arm64 yet, but x86_64 should work under arm64 in transcoder mode.
Prebuilt shaders for DX12 (as well for other GAPI) are uploaded with releases here https://github.com/GaijinEntertainment/DagorEngine/releases/download/dagor_2024_11_05/samples-prebuilt-game-windows.7z

**Comment by NicSavichev** [comment]
DX12 is disabled for x86 (32 bit mode) due to insufficient mapped memory, only x86_64 and arm64 will allow running dx12.
Recheck settings.blk, I definitely tested all samples to run with DX12, it should work.
And, of course, if you built samples with removed DX12 support (in jamfile - list of components for multi-driver) then you can't switch to it.

**Comment by CodeLikeCXK** [comment]
> DX12 is disabled for x86 (32 bit mode) due to insufficient mapped memory, only x86_64 and arm64 will allow running dx12. Recheck settings.blk, I definitely tested all samples to run with DX12, it should work. And, of course, if you built samples with removed DX12 support (in jamfile - list of components for multi-driver) then you can't switch to it.

I see. I have just checked that. Dx12 works but memory viewer is not available. Also there is memoryleak.

**Comment by CodeLikeCXK** [comment]
> DX12 is disabled for x86 (32 bit mode) due to insufficient mapped memory, only x86_64 and arm64 will allow running dx12. Recheck settings.blk, I definitely tested all samples to run with DX12, it should work. And, of course, if you built samples with removed DX12 support (in jamfile - list of components for multi-driver) then you can't switch to it.

Just check the draw_fps:b=yes, it's still dx11 even when dx12 is set(and it would use dx12 dlls)
![image](https://github.com/user-attachments/assets/d6229a23-5cd5-4f07-a829-b9c0acc1d0fe)

The jamfiles are not modified.

**Comment by NicSavichev** [comment]
Log may tell why DX11 is used instead of required DX12

**Comment by CodeLikeCXK** [comment]
> For arm64 I advise using DX12 as for my experience hardware with arm64 has poor support for DX11 (in drivers). Our big games built for arm64 (using DagorEngine) run on DX12 normally but crash randomly on DX11 (at least on MS minipc)

![image](https://github.com/user-attachments/assets/a28bd6f1-3b96-46e6-b18d-f022795ac98e)
I am using dx12 and every time I move there would be error(could be neglected though). You disable this when building?

**Comment by CodeLikeCXK** [comment]
![image](https://github.com/user-attachments/assets/8c756ab1-0964-4b86-847a-579ab25a260a)
![image](https://github.com/user-attachments/assets/d50b02c7-05ce-43d6-8cae-bec0b8993fd3)
Just neglect the error to make it run
