### ISSUE TITLE
Sample project for Enlisted?

### ISSUE THREAD

**Issue by VeresBalazsLaszlo** [GaijinEntertainment/DagorEngine#89]
Will a sample project similar to Gaija Island be released for Enlisted, as show in the documention? Or was the Berlin map was just shown as an example?

**Comment by NicSavichev** [comment]
Sample project based on daNetGame framework (basis for Enlisted and other newer games, except for WT) will be released soon.
As for Enlisted project it will definitely not go opensource so some references in documentation suits only need of documentation/

**Comment by NicSavichev** [comment]
https://github.com/GaijinEntertainment/DagorEngine/releases/tag/dagor_2024_12_04
OuterSpace is client-server game based on daNetGame framework.
dngSceneViewer is sample with shooter-like camera and character controller, not really shooter template (no weapons or damage model and no gameplay at all) but can be used to start writing shooter game.

**Comment by Capewearer** [comment]
Yes, I've seen update. That's really great!
