### ISSUE TITLE
de_dust2 is missing from testGI assets

### ISSUE THREAD

**Issue by DisrespectDwardo** [GaijinEntertainment/DagorEngine#9]
Hello, as seen in the settings.blk file included with testGI, there is a line showing that de_dust2 is supposed to be a loadable environment, however it is missing from the levels directory.

**Comment by deprale** [comment]
bump.

**Comment by NicSavichev** [comment]
> Hello, as seen in the settings.blk file included with testGI, there is a line showing that de_dust2 is supposed to be a loadable environment, however it is missing from the levels directory.

That comment was left from ancient times, right now we don't have de_dust sample int testGI.
I will check wether we can add it back to sample and return shortly

**Comment by NicSavichev** [comment]
Unfortunately we cannot upload de_dust2 content, so I will just remove that commented line from BLK for clarity.
