### ISSUE TITLE
Shader compilation for DX12 failed with error while building with windows arm64

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#90]
![image](https://github.com/user-attachments/assets/dfdf87ba-be25-45a9-b55a-b9eb528aeac1)
 "no valid shader compiler library handle provide"

**Comment by NicSavichev** [comment]
I think main problem is shader compiler was not compiled for windows-arm64 and was never tested (it should use DXC library that may be not-arm64-ready). So we compile shaders with x86_64 and just use result in game.
I will look later is it possible to build and use tools in native arm64
