### ISSUE TITLE
Fail to compile heightmapland for windows arm64 due to codes related to emmitrin:How to retarget the feature for platform other than SSE?

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#91]
![image](https://github.com/user-attachments/assets/676ae250-4abd-4d68-954f-796dbdb320f6)
![image](https://github.com/user-attachments/assets/0d96fdba-5118-4dd5-ba0e-5e4e93c9a975)

#if _TARGET_PC && _TARGET_SIMD_SSE
  bool build(uint32_t cellsX, uint32_t cellsY, float cellSz, const Point3 &ofs, const BBox3 &box, dag::ConstSpan<Mesh *> meshes,
    dag::ConstSpan<Mesh *> combined_meshes, uint32_t min_grid_index, uint32_t max_grid_index, bool optimize_for_cache);
#endif

Which part of this code may related to SSE? What is its NEON counterpart?

**Comment by NicSavichev** [comment]
Since it is used only in tools I temporarily disabled that code with ifdef/
It needs to be rewritten using ARM NEON or scalar math.
We only built and ran games for windows-arm64, not tools. Tools are used on normal machines with x86_64

**Comment by CodeLikeCXK** [comment]
> Since it is used only in tools I temporarily disabled that code with ifdef/ It needs to be rewritten using ARM NEON or scalar math. We only built and ran games for windows-arm64, not tools. Tools are used on normal machines with x86_64

I see. How much diable related codes that use bulld function influence the editor function? Which part of it should be replaced?

**Comment by NicSavichev** [comment]
> I see. How much diable related codes that use bulld function influence the editor function? Which part of it should be replaced?

It is used to export landmesh and raytracer for it here
[X:\DagorEngine.git\prog\tools\sceneTools\daEditorX\HeightmapLand\importLandMesh.cpp](https://github.com/GaijinEntertainment/DagorEngine/blob/main/prog/tools/sceneTools/daEditorX/HeightmapLand/importLandMesh.cpp#L848)
and similar places. So landscape plugin for daEditorX will fail to build.
Other tools should be built ok and can be used.

**Comment by CodeLikeCXK** [comment]
> > I see. How much diable related codes that use bulld function influence the editor function? Which part of it should be replaced?
> 
> It is used to export landmesh and raytracer for it here [X:\DagorEngine.git\prog\tools\sceneTools\daEditorX\HeightmapLand\importLandMesh.cpp](https://github.com/GaijinEntertainment/DagorEngine/blob/main/prog/tools/sceneTools/daEditorX/HeightmapLand/importLandMesh.cpp#L848) and similar places. So landscape plugin for daEditorX will fail to build. Other tools should be built ok and can be used.

By the way I just found a file that might include some 'redirections' to emmitrins used in landscape rayyracing function which might be useful
https://github.com/lighttransport/embree-aarch64/blob/master/common/math/SSE2NEON.h
