### ISSUE TITLE
DaScript AOT compilation failed for windows arm64 platform

### ISSUE THREAD

**Issue by CodeLikeCXK** [GaijinEntertainment/DagorEngine#93]
![image](https://github.com/user-attachments/assets/8e45cc1c-a57c-41b7-a10e-2a78c5809c99)
While build_aot_compiler_arm64 success, building DasAOT for OuterSpace sample failed.
How might this be related to?

**Comment by NicSavichev** [comment]
Mind that currently AOT is built for x86_64 (in order to be run on x86_64 machine) and game itself can be built for arm64
Though it fails for me on start (with both vc16 and vc17) due to code in static ctor inside Jolt phys library. I'm investigating how to fix it and will push update to code.
Compile and link both work for me in master
```
buildStamp.c
linking outer_space-dev.exe
lld-link: warning: section name .debug_abbrev is longer than 8 characters and will use a non-standard string table
lld-link: warning: section name .debug_aranges is longer than 8 characters and will use a non-standard string table
lld-link: warning: section name .debug_info is longer than 8 characters and will use a non-standard string table
lld-link: warning: section name .debug_line is longer than 8 characters and will use a non-standard string table
----------------------------------------------------------------------
SUCCESSFULLY built outer_space-dev.exe  [windows-100~arm64~dev~vc16-16.11.34~m~s4~c]
```

**Comment by CodeLikeCXK** [comment]
> Mind that currently AOT is built for x86_64 (in order to be run on x86_64 machine) and game itself can be built for arm64 Though it fails for me on start (with both vc16 and vc17) due to code in static ctor inside Jolt phys library. I'm investigating how to fix it and will push update to code. Compile and link both work for me in master
> 
> ```
> buildStamp.c
> linking outer_space-dev.exe
> lld-link: warning: section name .debug_abbrev is longer than 8 characters and will use a non-standard string table
> lld-link: warning: section name .debug_aranges is longer than 8 characters and will use a non-standard string table
> lld-link: warning: section name .debug_info is longer than 8 characters and will use a non-standard string table
> lld-link: warning: section name .debug_line is longer than 8 characters and will use a non-standard string table
> ----------------------------------------------------------------------
> SUCCESSFULLY built outer_space-dev.exe  [windows-100~arm64~dev~vc16-16.11.34~m~s4~c]
> ```

I see....The executable did compile but it couldn't launch maybe due to lacking scripts(AOT fails)

**Comment by CodeLikeCXK** [comment]
Thanks! Now OuterSpace built on windows arm64 now
![image](https://github.com/user-attachments/assets/140e72b0-5783-4840-a561-4e3db6a827d7)
